baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.smish.dev" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/page/:num"

collections:
  rocket_league:
    output: true
    permalink: /rocket_league/:title
  math:
    output: true
    permalink: /math/:title


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
